# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ben Goff History
email: bengoff5017@gmail.com
description: >
  My personal website, <br>
  with lots of fun history stuff, <br>
  especially on French military hospitals!
tagline: vitam impendere vero
location: Tallahassee
date: true
baseurl: "/bengoffhistory" # the subpath of your site, e.g. /blog
url: "https://bengoff1.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author: “To conserve more and spend less, such is the philosophical and economic problem of hospitals. The legislator cannot weigh the life or liberty of a citizen against some monetary value, but at the same time he must not drain public funds, nor can he spare no expense to ease human suffering.”- Claude Boyer, Eighteenth-Century French Military Surgeon 
google_analytics: UA-101394056-1

# Build settings
exclude: README.md
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
plugins_dir:
  - jekyll-roman
  - jekyll-seo-tag
